env:
  global:
    - ANDROID_API_LEVEL=27
    - EMULATOR_API_LEVEL=22
    - ANDROID_BUILD_TOOLS_VERSION=27.0.3
    - ANDROID_ABI="default;armeabi-v7a"
    - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)
    - ios_device="iPhone 7"
    - ios_version=10.3
matrix:
  # This causes the build to complete immediately upon first failure or once
  # required jobs are green.
  fast_finish: true

  # Building APK/IPA takes a long time; do not wait for them to finish.
  allow_failures:
#    - env: JOB=DRIVER-ANDROID
    - env: JOB=DRIVER-IOS

  include:
    # Runs unit tests without emulators.
    - env: JOB=TEST
      os: linux
      language: generic
      sudo: false
      addons:
        apt:
          # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
          sources:
            - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
          packages:
            - libstdc++6
            - fonts-droid
      before_script:
        - git clone https://github.com/flutter/flutter.git -b beta
        - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
        - flutter doctor
        - pub global activate coverage
      script:
        - ./script/runTests.sh
      after_success:
        - bash <(curl -s https://codecov.io/bash) -f lcov.info

    # Builds and runs driver on ios.
    - env: JOB=DRIVER-IOS
      os: osx
      language: generic
      osx_image: xcode9.0
      before_script:
        - open /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app
        - brew update
        - brew install libimobiledevice || echo 'ignore exit(1)'
        - brew install ideviceinstaller
        - brew install ios-deploy
        - brew install cocoapods || echo 'ignore exit(1)'
        - brew link --overwrite cocoapods
        - git clone https://github.com/flutter/flutter.git -b beta
        - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
        - flutter precache
        - flutter doctor
        - flutter upgrade
        - flutter devices
      script:
        - ./script/runDriver.sh

cache:
  directories:
    - $HOME/.pub-cache