name: blocs
description: The Business Logic Components for a Todo App

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  todos_repository:
    path: ../todos_repository
  rxdart: "^0.16.1"

dev_dependencies:
  test: ^0.12.0
  mockito: "^2.2.3"
