name: firebase_flutter_repository
description: A reactive version of the todos repository for Flutter

dependencies:
  flutter:
    sdk: flutter
  todos_repository:
    path: ../todos_repository
  firebase_auth: 0.5.3
  cloud_firestore: 0.5.1

dev_dependencies:
  mockito: ">=2.2.0 <3.0.0"
  flutter_test:
    sdk: flutter
